# Generated by Django 5.0.6 on 2024-06-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('shortname', models.CharField(max_length=5)),
                ('stockname', models.CharField(max_length=200)),
                ('option', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4)),
                ('quantity', models.IntegerField(max_length=9999)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
